"""initial_migration

Revision ID: 2f06e8051c2d
Revises: 
Create Date: 2026-06-11 03:26:21.922796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f06e8051c2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_post_heart_uc', 'hearts', ['user_id', 'post_id'])
    op.drop_constraint(op.f('hearts_user_id_fkey'), 'hearts', type_='foreignkey')
    op.create_foreign_key(None, 'hearts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('images_post_id_fkey'), 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(op.f('images_post_id_fkey'), 'images', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'hearts', type_='foreignkey')
    op.create_foreign_key(op.f('hearts_user_id_fkey'), 'hearts', 'users', ['user_id'], ['id'])
    op.drop_constraint('_user_post_heart_uc', 'hearts', type_='unique')
    # ### end Alembic commands ###
